services:
  - type: web
    name: tsf-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r ../requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"

  - type: web
    name: tsf-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "build"
    envVars:
      - key: REACT_APP_API_URL
        value: https://tsf-backend.onrender.com
